name: Python Linter (Flake8)

# [span_0](start_span)Requisito: "to run in each pull to the main branch"[span_0](end_span)
on:
pull_request:
branches: [ main ]

jobs:
lint:
runs-on: ubuntu-latest
steps:
# 1. Clona el código del PR
- name: Check out repository code
uses: actions/checkout@v4

# 2. Configura Python
- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.10'

# 3. Instala Flake8
- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install flake8

# 4. Ejecuta el linter
- name: Lint with Flake8
run: |
flake8 . --count --show-source --statistics